export const CHANGE_CURRENT_SONG = "play/CHANGE_CURRENT_SONG";
export const CHANGE_LYRICS = "play/CHANGE_LYRICS";

export const CHANGE_PLAY_LIST = "play/CHANGE_PLAY_LIST";
export const CHANGE_CURRENT_SONG_INDEX = "play/CHANGE_CURRENT_SONG_INDEX";
export const CHANGE_PLAY_SEQUENCE = "play/CHANGE_PLAY_SEQUENCE";

export const CHANGE_CURRENT_LYRIC_INDEX = "play/CHANGE_CURRENT_LYRIC_INDEX";
export const CHANGE_CURRENT_LYRIC = "play/CHANGE_CURRENT_LYRIC";
